//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukseklisansProje.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruTablosu
    {
        public int ID { get; set; }
        public int Fk_KisiID { get; set; }
        public int Fk_ProgramID { get; set; }
        public string Dekont { get; set; }
        public Nullable<System.DateTime> BasvuruTarihi { get; set; }
        public string IpAdresi { get; set; }
        public Nullable<int> Fk_SecilenLisansID { get; set; }
        public Nullable<int> Fk_SecilenSinavID { get; set; }
        public Nullable<int> Fk_SecilenYuksekLisansID { get; set; }
        public string Sonuc { get; set; }
    
        public virtual KisiTablosu KisiTablosu { get; set; }
        public virtual LisansTablosu LisansTablosu { get; set; }
        public virtual SinavTablosu SinavTablosu { get; set; }
        public virtual LisansTablosu LisansTablosu1 { get; set; }
    }
}
