//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukseklisansProje.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuncellemeTablosu
    {
        public int ID { get; set; }
        public int Fk_KisiID { get; set; }
        public int Fk_GuncellemeYapanID { get; set; }
        public System.DateTime GuncellemeTarihi { get; set; }
        public string IpAdresi { get; set; }
    
        public virtual KisiTablosu KisiTablosu { get; set; }
    }
}
