//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukseklisansProje.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisiTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KisiTablosu()
        {
            this.BasvuruTablosu = new HashSet<BasvuruTablosu>();
            this.GuncellemeTablosu = new HashSet<GuncellemeTablosu>();
            this.LisansTablosu = new HashSet<LisansTablosu>();
            this.SinavTablosu = new HashSet<SinavTablosu>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string BabaAdi { get; set; }
        public long TC { get; set; }
        public string Sifre { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<long> Telefon { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public string Fotograf { get; set; }
        public Nullable<System.DateTime> KayitZamani { get; set; }
        public string IpAdresi { get; set; }
        public Nullable<bool> YoneticiMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruTablosu> BasvuruTablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuncellemeTablosu> GuncellemeTablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LisansTablosu> LisansTablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinavTablosu> SinavTablosu { get; set; }
    }
}
