//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukseklisansProje.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtomasyonDBEntities : DbContext
    {
        public OtomasyonDBEntities()
            : base("name=OtomasyonDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BasvuruTablosu> BasvuruTablosu { get; set; }
        public virtual DbSet<BolumTablosu> BolumTablosu { get; set; }
        public virtual DbSet<EgitimTuru> EgitimTuru { get; set; }
        public virtual DbSet<FakulteTablosu> FakulteTablosu { get; set; }
        public virtual DbSet<GuncellemeTablosu> GuncellemeTablosu { get; set; }
        public virtual DbSet<KisiTablosu> KisiTablosu { get; set; }
        public virtual DbSet<LisansTablosu> LisansTablosu { get; set; }
        public virtual DbSet<ProgramTablosu> ProgramTablosu { get; set; }
        public virtual DbSet<SinavTablosu> SinavTablosu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UniversiteTablosu> UniversiteTablosu { get; set; }
    }
}
