//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukseklisansProje.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinavTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinavTablosu()
        {
            this.BasvuruTablosu = new HashSet<BasvuruTablosu>();
        }
    
        public int ID { get; set; }
        public int Fk_KisiID { get; set; }
        public string SinavTuru { get; set; }
        public decimal Puan { get; set; }
        public string SinavSonucBelgesi { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string IpAdresi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruTablosu> BasvuruTablosu { get; set; }
        public virtual KisiTablosu KisiTablosu { get; set; }
    }
}
